steps:
  - name: 'python:3.12'
    id: 'Install and Run Tests'
    entrypoint: 'sh'
    args:
      - |
        pip install -r requirements.txt
        python -m playwright install --with-deps chromium
        pytest --html=reports/index.html
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
