version: 2.1

jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Install Playwright Browser
          command: python -m playwright install --with-deps chromium
      
      - run:
          name: Run tests
          command: pytest --html=reports/index.html

      - store_artifacts:
          path: reports
          destination: test-results
  
workflows:
  build-and-test:
    jobs:
      - test-python